import type { Case, Comment, Doc, Post, Sponsor, Subscriber } from '@/lib/types'

export const seedCases: Case[] = [
  {
    id: 'c1',
    title: 'Pose implant unitaire secteur 46',
    specialty: 'Implantologie',
    type: 'video',
    duration: '12 min',
    description: 'Extraction-implantation immédiate avec mise en charge.',
    media_url: null,
    media_urls: [],
    premium: false,
    sensitive: true,
  },
  {
    id: 'c2',
    title: 'Greffe osseuse autogène mandibulaire',
    specialty: 'Greffe osseuse',
    type: 'video',
    duration: '18 min',
    description: 'Prélèvement ramique et fixation par vis d’ostéosynthèse.',
    media_url: null,
    media_urls: [],
    premium: true,
    sensitive: true,
  },
  {
    id: 'c3',
    title: 'Sinus lift par abord latéral',
    specialty: 'Sinus lift',
    type: 'photo',
    duration: '',
    description: 'Comblement sous-sinusien, biomatériau xénogénique.',
    media_url: null,
    media_urls: [],
    premium: true,
    sensitive: true,
  },
  {
    id: 'c4',
    title: 'Extraction dent de sagesse incluse',
    specialty: 'Extraction',
    type: 'video',
    duration: '9 min',
    description: 'Germectomie 38 en position mésio-angulée.',
    media_url: null,
    media_urls: [],
    premium: false,
    sensitive: true,
  },
  {
    id: 'c5',
    title: 'Lambeau d’assainissement parodontal',
    specialty: 'Parodontologie',
    type: 'photo',
    duration: '',
    description: 'Débridement à ciel ouvert secteur antérieur.',
    media_url: null,
    media_urls: [],
    premium: true,
    sensitive: true,
  },
  {
    id: 'c6',
    title: 'Régénération osseuse guidée (ROG)',
    specialty: 'Greffe osseuse',
    type: 'video',
    duration: '16 min',
    description: 'Membrane résorbable + particules d’os.',
    media_url: null,
    media_urls: [],
    premium: true,
    sensitive: true,
  },
  {
    id: 'c7',
    title: 'Implant + provisoire immédiat secteur 21',
    specialty: 'Implantologie',
    type: 'photo',
    duration: '',
    description: 'Zone esthétique, gestion du profil d’émergence.',
    media_url: null,
    media_urls: [],
    premium: false,
    sensitive: false,
  },
  {
    id: 'c8',
    title: 'Comblement alvéolaire post-extraction',
    specialty: 'Extraction',
    type: 'photo',
    duration: '',
    description: 'Préservation de crête, technique socket-shield.',
    media_url: null,
    media_urls: [],
    premium: true,
    sensitive: true,
  },
]

export const seedDocs: Doc[] = [
  {
    id: 'd1',
    title: 'Mise en charge immédiate : revue systématique',
    journal: 'Journal of Oral Implantology',
    year: '2025',
    pdf_url: null,
    premium: false,
  },
  {
    id: 'd2',
    title: 'Protocoles de greffe osseuse guidée — fiche technique',
    journal: 'Protocole interne',
    year: '2026',
    pdf_url: null,
    premium: true,
  },
  {
    id: 'd3',
    title: 'Taux de survie implantaire à 10 ans',
    journal: 'Clinical Oral Implants Research',
    year: '2024',
    pdf_url: null,
    premium: true,
  },
  {
    id: 'd4',
    title: 'Gestion des tissus mous péri-implantaires',
    journal: 'Perio & Implant Digest',
    year: '2025',
    pdf_url: null,
    premium: true,
  },
  {
    id: 'd5',
    title: 'Antibioprophylaxie en chirurgie orale',
    journal: 'Recommandations HAS',
    year: '2023',
    pdf_url: null,
    premium: false,
  },
]

export const seedPosts: Post[] = [
  {
    id: 'p1',
    title: 'Comprendre l’implant dentaire en 5 étapes',
    category: 'Pédagogie',
    excerpt: 'Le parcours complet, de la consultation à la couronne définitive.',
    cover_url: null,
    date: '8 juil. 2026',
  },
  {
    id: 'p2',
    title: 'Pourquoi documenter chaque intervention ?',
    category: 'Coulisses',
    excerpt: 'Transparence pour les patients, transmission pour les confrères.',
    cover_url: null,
    date: '2 juil. 2026',
  },
  {
    id: 'p3',
    title: 'Sinus lift : à quoi s’attendre ?',
    category: 'Pédagogie',
    excerpt: 'Indications, déroulé et suites opératoires expliqués simplement.',
    cover_url: null,
    date: '24 juin 2026',
  },
  {
    id: 'p4',
    title: 'Nouveautés 2026 en implantologie guidée',
    category: 'Innovation',
    excerpt: 'Planification 3D et chirurgie naviguée : où en est-on ?',
    cover_url: null,
    date: '12 juin 2026',
  },
]

export const seedSponsors: Sponsor[] = [
  { id: 'sp1', name: 'Straumann', logo_url: null, url: null },
  { id: 'sp2', name: 'Nobel Biocare', logo_url: null, url: null },
  { id: 'sp3', name: 'Dentsply Sirona', logo_url: null, url: null },
  { id: 'sp4', name: 'Geistlich', logo_url: null, url: null },
  { id: 'sp5', name: 'MIS Implants', logo_url: null, url: null },
  { id: 'sp6', name: 'BioHorizons', logo_url: null, url: null },
]

export const seedComments: Comment[] = [
  { id: 'cm1', case_id: 'c1', author: 'Dr. Laurent M.', body: 'Documentation très claire, merci pour le partage.', approved: true },
  { id: 'cm2', case_id: 'c1', author: 'Étudiant DFASO2', body: 'Le déroulé étape par étape aide beaucoup pour la révision.', approved: true },
]

export const seedSubscribers: Subscriber[] = [
  {
    id: 's1',
    name: 'Dr. Laurent M.',
    initial: 'L',
    plan: 'Praticien (annuel)',
    since: 'Jan. 2026',
    status: 'active',
  },
  {
    id: 's2',
    name: 'Clinique Odonto Nord',
    initial: 'C',
    plan: 'Institution',
    since: 'Nov. 2025',
    status: 'active',
  },
  {
    id: 's3',
    name: 'Dr. Amira B.',
    initial: 'A',
    plan: 'Praticien (mensuel)',
    since: 'Mars 2026',
    status: 'active',
  },
  {
    id: 's4',
    name: 'Étudiant · Fac Dentaire',
    initial: 'É',
    plan: 'Découverte',
    since: 'Fév. 2026',
    status: 'free',
  },
  {
    id: 's5',
    name: 'Dr. Sofiane R.',
    initial: 'S',
    plan: 'Praticien (mensuel)',
    since: 'Avr. 2026',
    status: 'paused',
  },
]
